apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-pod
spec:
  containers:
  - name: mycontainer
    image: busybox
    command:
      - 'sh'
      - '-c'
      - 'cat /etc/credentials/username; echo " "; cat /etc/credentials/password; sleep 360'
    volumeMounts:
    - name: foo
      mountPath: "/etc/credentials"
  volumes:
  - name: foo
    secret:
      secretName: db-user-pass
      defaultMode: 0400
