
# pod-watch Pod in the auth namespace
# get and list Pods and Pod logs in the auth namespace.
# Create a service account called pod-monitor and assign it appropriate RBAC permissions for the pod-watch Pod.

apiVersion: v1
kind: Namespace
metadata:
  name: auth

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-monitor
  namespace: auth
automountServiceAccountToken: false

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: auth
  name: pod-watch-r
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-watch-rb
  namespace: auth
subjects:
- kind: ServiceAccount
  name: pod-monitor
  namespace: auth
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pod-watch-r # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

--- 

apiVersion: v1
kind: Pod
metadata:
  name: pod-watch
  namespace: auth
spec:
  containers:
  - image: radial/busyboxplus:curl
    name: watcher
    command: ['sh', '-c', 'TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token); while true; do if curl -s -o /dev/null -k -m 3 -H "Authorization: Bearer $TOKEN" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/auth/pods/; then echo "[SUCCESS] Successfully viewed Pods!"; else echo "[FAIL] Failed to view Pods!"; fi; sleep 5; done']
  serviceAccountName: pod-monitor
   
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-watch-logs
  namespace: auth
spec:
  containers:
  - image: radial/busyboxplus:curl
    name: watcher
    command: ['sh', '-c', 'TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token); while true; do if curl -s -o /dev/null -k -m 3 -H "Authorization: Bearer $TOKEN" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/auth/pods/pod-watch/log; then echo "[SUCCESS] Successfully viewed pod-watch logs!"; else echo "[FAIL] Failed to view pod-watch log!"; fi; sleep 5; done']
  serviceAccountName: pod-monitor
