apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ng-dep
  name: ng-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ng-dep
  strategy: {}
  template:
    metadata:
      labels:
        app: ng-dep
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 3000
        resources: {}
status: {}