apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-auth-sa-psp
  namespace: auth
roleRef:
  kind: ClusterRole
  name: cr-use-psp-no-privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: auth-sa
  namespace: auth